/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("renters.problem.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":simplex"))
}

application {
    // Define the main class for the application.
    mainClass.set("renters.problem.app.App")
}
